### ISSUE TITLE
black bishops captured on c8 and f8 plus one more white pawn capture

### ISSUE THREAD

**Issue by hwatheod** [miguel-ambrona/sherlock#38]
Sherlock doesn't detect this position as illegal: `4k2r/pp1pp1p1/1np2n1p/qr3p2/2PP1N1P/B1PQP1PB/P2KNPR1/R7 b - -`

![Issue](https://backscattering.de/web-boardimage/board.svg?fen=4k2r/pp1pp1p1/1np2n1p/qr3p2/2PP1N1P/B1PQP1PB/P2KNPR1/R7)

It is illegal because there are too many white captures: White captured the black bishops on c8, f8, plus one more pawn capture on the c-file.

**Comment by miguel-ambrona** [comment]
Thanks for this!

This will be captured automatically when we introduce non-deterministic rules to make pawn origins concrete.

I'll consider handling it in a different way though.
