### ISSUE TITLE
White back rank captures plus one more capture

### ISSUE THREAD

**Issue by hwatheod** [miguel-ambrona/sherlock#39]
Sherlock doesn't detect this position as illegal: `rn2kb2/pp5p/2bppp2/2p2p2/2Nq4/5N2/PPPPPPPP/2B1KB2 b - -`

![Issue](https://backscattering.de/web-boardimage/board.svg?fen=rn2kb2/pp5p/2bppp2/2p2p2/2Nq4/5N2/PPPPPPPP/2B1KB2)

White R+Q+R were captured on the first rank, plus one more Black pawn capture on the f-file, is too many.

**Comment by miguel-ambrona** [comment]
As in #38 , non-determinism will fix this. 

I'll think about alternatives.

**Comment by miguel-ambrona** [comment]
Fixed in #48
