### ISSUE TITLE
Illegal bishop and pawn configuration in the corner

### ISSUE THREAD

**Issue by hwatheod** [miguel-ambrona/sherlock#41]
Sherlock doesn't detect this position as illegal: `4k3/8/8/8/8/1P6/bPP5/1b2K3 b - -`

![Issue](https://backscattering.de/web-boardimage/board.svg?fen=4k3/8/8/8/8/1P6/bPP5/1b2K3)

The bishop and pawn configuration in the corner is illegal.

**Comment by miguel-ambrona** [comment]
This is kind of similar to #40.
