### ISSUE TITLE
white king and queen illegally switched on the first rank

### ISSUE THREAD

**Issue by hwatheod** [miguel-ambrona/sherlock#42]
Sherlock doesn't detect this position as illegal: `2b4r/p2p1pp1/2p1r2p/1p2q1k1/P1Nnp3/8/1PPPPPPP/R1B1KQ1R w - -`

![Issue](https://backscattering.de/web-boardimage/board.svg?fen=2b4r/p2p1pp1/2p1r2p/1p2q1k1/P1Nnp3/8/1PPPPPPP/R1B1KQ1R)

The white king and queen are illegally switched on the first rank.

**Comment by miguel-ambrona** [comment]
Nice! With any white castling enabled this would already be identified as illegal.

Any ideas on how to fix this?

**Comment by hwatheod** [comment]
This one (and the similar number 43) is hardcoded as a rule into Retractor. If the king and queen never left the first rank, then their order cannot be switched.  There are many similar ordering rules, [described here](https://github.com/hwatheod/retractor/blob/4a10becdc6ddca4eb8c096b6ccd07107ea0d144a/cages.js#L439).  (A note on terminology: Retractor 'frozen' = Sherlock 'steady')
