### ISSUE TITLE
Illegal ordering of White rook, queen, king on the first rank

### ISSUE THREAD

**Issue by hwatheod** [miguel-ambrona/sherlock#43]
Sherlock doesn't detect this position as illegal: `3r3r/p2p1p1p/b1p2kp1/1p1npq1n/P7/8/1PPPPPPP/RNB2RQK w - -`

![Issue](https://backscattering.de/web-boardimage/board.svg?fen=3r3r/p2p1p1p/b1p2kp1/1p1npq1n/P7/8/1PPPPPPP/RNB2RQK)

The order of the White rook, queen, king on the first rank is impossible.

On the kingside, QKR and QRK (because of castling) are possible, but not RQK.

**Comment by miguel-ambrona** [comment]
Same as #42.

I guess a cage rule... Although it seems too specific.
I would love to find something more general than that.
